version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Dockerfile with hadolint
          command: |
            hadolint Dockerfile

  test-app:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run:
          name: Run unit test
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: circleci/base:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push app image
          command: ./build_push_image_karsajobs.sh
          
workflows:
  build-and-test:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
